#!/usr/bin/env php
<?php

$autoloadFileName = __DIR__.'/../../autoload.php';

if (! file_exists($autoloadFileName)) {
    // autoload for development.
    $autoloadFileName = __DIR__.'/vendor/autoload.php';
}

require_once $autoloadFileName;

use ThenLabs\Cli\Application;

$application = new Application;

$application->run();
